pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - task: InstallMATLAB@0
  - task: RunMATLABCommand@0
    inputs: 
      command: disp('Hello World');disp('Hello World2');disp("Hello World2");plot(1:10, 1:10);x=1+1;disp(x); ls; pwd; cd;pwd; !echo hoge;!dir;!ls -al;!ls; !echo $PATH; 
