 pool:
   vmImage: 'Ubuntu 16.04'
 steps:
   - script: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
   - task: RunMATLABCommand@0
     inputs: 
       command: disp('Hello World')
