version: 2.1
orbs:
  matlab: mathworks/matlab@0.1.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command: 
          command: disp('Hello World');disp('Hello World2');disp("Hello World2");plot(1:10, 1:10);x=1+1;disp(x); ls; pwd; cd;pwd; !echo hoge;!dir;!ls -al;!ls; !echo $PATH; 

