version: 2.1
orbs:
  matlab: mathworks/matlab@0.1.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command: 
          command: doc assert;
