version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - matlab/run-command: 
          command: disp('Hello World')
